# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\x06master\"\xd5\x01\n\x0eMessageRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x04\x12\x12\n\nchannel_id\x18\x04 \x01(\x04\x12\x11\n\tcreate_at\x18\x05 \x01(\x04\x12\x11\n\tupdate_at\x18\x06 \x01(\x04\x12\x0f\n\x07root_id\x18\x07 \x01(\x04\x12\x0f\n\x07\x65\x64it_at\x18\x08 \x01(\x04\x12\x11\n\tdelete_at\x18\t \x01(\x04\x12\x11\n\tis_pinned\x18\n \x01(\x08\x12\x13\n\x0boriginal_id\x18\x0b \x01(\x04\"\xfe\x01\n\x0eMessageRespons\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x04\x12\x12\n\nchannel_id\x18\x04 \x01(\x04\x12\x11\n\tcreate_at\x18\x05 \x01(\x04\x12\x11\n\tupdate_at\x18\x06 \x01(\x04\x12\x0f\n\x07root_id\x18\x07 \x01(\x04\x12\x0f\n\x07\x65\x64it_at\x18\x08 \x01(\x04\x12\x11\n\tdelete_at\x18\t \x01(\x04\x12\x11\n\tis_pinned\x18\n \x01(\x08\x12\x13\n\x0boriginal_id\x18\x0b \x01(\x04\x12\x17\n\x0frespons_message\x18\x0c \x01(\t\x12\x0e\n\x06status\x18\r \x01(\t\"&\n\x14\x43reateMessageRespons\x12\x0e\n\x06status\x18\x01 \x01(\t2V\n\rMasterService\x12\x45\n\rCreateMessage\x12\x16.master.MessageRequest\x1a\x1c.master.CreateMessageResponsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=25
  _globals['_MESSAGEREQUEST']._serialized_end=238
  _globals['_MESSAGERESPONS']._serialized_start=241
  _globals['_MESSAGERESPONS']._serialized_end=495
  _globals['_CREATEMESSAGERESPONS']._serialized_start=497
  _globals['_CREATEMESSAGERESPONS']._serialized_end=535
  _globals['_MASTERSERVICE']._serialized_start=537
  _globals['_MASTERSERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
